### ISSUE TITLE
Fetching geobject by code on the CGR adapter without the typeCode throws an exception

### ISSUE THREAD

**Issue by ekigamba** [terraframe/common-geo-registry-adapter#12] opened 2019-02-07 07:18 UTC
Currently, one can perform a request for a geo-object on the following URL https://georegistry-domain.com/cgr/geoobject/get-code?code=855%2001 without providing the `typeCode`. The same operation when performed on the CGR adapter with either `null` for the `typeCode` throws an NPE.

I think that it should be possible to make the call on the CGR adapter without the typeCode as in the CGR API.

@justinlewis What do you think?

**Comment by justinlewis** [comment] 2019-02-07 20:43
I think this is a bug that we fixed in our current sprint which will be released soon. 

The intended behavior is to require a typeCode for performance reasons.

**Comment by rrowlands** [comment] 2019-03-12 22:24
This is correct. In our REST API, when referencing a GeoObject by id you must always provide the type information. We don't envision this behavior changing anytime soon.

**Closed as completed by rrowlands** 2019-03-12 22:24 UTC
Labels: bug
