### ISSUE TITLE
Server errors when trying to refresh the metadata cache and populating the IDs

### ISSUE THREAD

**Issue by justinlewis** [terraframe/common-geo-registry-adapter#11] opened 2019-01-23 20:56 UTC
I started getting 500 errors after the first run at the API on the sample android app. I got these errors when trying to refresh the metadata cache and populating the IDs. This issue seems to happen after sometime. Are you guys doing development on the server. Otherwise, these are issue(s) that need to be looked at in case this is to go to production for use in Reveal. It seems to be a problem with having too many sessions logged in, what is the expectation when using it?

Issue submitted by Ona

**Comment by rrowlands** [comment] 2019-01-30 17:03
This highlights a weakness in our error handling and recovery mechanism and processes for the CGR adapter. The first problem is that you guys were not given more information as far as exactly what the issue is (perhaps an exception with a message). In this case I suspect that you are correct that the hidden exception here is too many sessions. The second problem is we need to have a better defined workflow and process for submitting bug reports which includes the time at which the bug occurred (otherwise I can't check the logs). Additionally, this bug report process needs to include the version of the CGR adapter in which the bug was found, which makes it clear to us that we need to be releasing formal versions of the adapter to maven central. To summarize the problems discovered with this ticket:

1. Errors are not handled properly in the CGR android adapter, especially Session related errors.
2. We need a bug template which includes (at least): the time that the bug occurred on our server and the version of the android adapter
3. The CGR android adapter may be logging in and out too many times and/or otherwise improperly managing sessions.
4. We need to start doing formal CGR adapter releases so that you guys don't have to use snapshots.

**Comment by justinlewis** [comment] 2019-01-30 19:26
Regarding the templates and ticket workflow I'll work on setting up some templates so that it's easier to know what we need in an issue report. Sorry for not doing that earlier. It took this issue to highlight the need.

**Comment by rrowlands** [comment] 2019-02-16 02:47
The session leak error should be fixed in our latest GeoRegistry release. Thanks for your input @ekigamba. Let us know if you continue to have issues.

**Closed as completed** 2022-06-28 15:22 UTC
Labels: bug
